"use client";

import { useState, useEffect, useRef } from "react";
import Editor, { OnMount } from "@monaco-editor/react";
import { 
  FolderOpen, FileText, ChevronRight, ChevronDown, Play, Sparkles, 
  ShieldCheck, AlertTriangle, Terminal as TerminalIcon, RotateCcw, Check, Zap, Layers 
} from "lucide-react";

declare global {
  interface Window {
    electronAPI?: {
      openFolder: () => Promise<{ folderPath: string; tree: any } | null>;
      readDir: (path: string) => Promise<any>;
      readFile: (path: string) => Promise<{ success: boolean; content?: string; error?: string }>;
      analyzeFile: (path: string) => Promise<any>;
      safeRemove: (path: string, lines: number[]) => Promise<any>;
    };
  }
}

interface FileNode {
  name: string;
  path: string;
  isDirectory: boolean;
  children?: FileNode[];
}

interface Finding {
  line: number;
  code: string;
  title: string;
  reason: string;
  luminance: number;
  status: string;
}

const defaultMockTree: FileNode = {
  name: "ai_cart_project",
  path: "/mock/ai_cart_project",
  isDirectory: true,
  children: [
    {
      name: "src",
      path: "/mock/ai_cart_project/src",
      isDirectory: true,
      children: [
        { name: "cart_calculator.py", path: "/mock/ai_cart_project/src/cart_calculator.py", isDirectory: false },
        { name: "checkout_engine.py", path: "/mock/ai_cart_project/src/checkout_engine.py", isDirectory: false },
        { name: "invoice_processor.py", path: "/mock/ai_cart_project/src/invoice_processor.py", isDirectory: false },
      ],
    },
    { name: "nullity.toml", path: "/mock/ai_cart_project/nullity.toml", isDirectory: false },
    { name: "README.md", path: "/mock/ai_cart_project/README.md", isDirectory: false },
  ],
};

const defaultSampleCode = `def calculate_cart_total(items, discount):
    # Calculate subtotal across items
    subtotal = sum(item.price for item in items)
    
    # Vacuous identity operations generated by AI
    subtotal = subtotal * 1
    subtotal = subtotal + 0
    subtotal = subtotal - 0
    subtotal = subtotal / 1
    
    final_total = subtotal - discount
    return max(0, final_total)
`;

export default function IDEApp() {
  const [folderPath, setFolderPath] = useState<string | null>("/mock/ai_cart_project");
  const [fileTree, setFileTree] = useState<FileNode | null>(defaultMockTree);
  const [openTabs, setOpenTabs] = useState<{ path: string; name: string; content: string }[]>([
    {
      path: "/mock/ai_cart_project/src/cart_calculator.py",
      name: "cart_calculator.py",
      content: defaultSampleCode,
    },
  ]);
  const [activeTabPath, setActiveTabPath] = useState<string | null>("/mock/ai_cart_project/src/cart_calculator.py");
  const [expandedFolders, setExpandedFolders] = useState<Record<string, boolean>>({
    "/mock/ai_cart_project": true,
    "/mock/ai_cart_project/src": true,
  });
  const [editorContent, setEditorContent] = useState<string>(defaultSampleCode);
  const [findings, setFindings] = useState<Finding[]>([
    {
      line: 6,
      code: "subtotal = subtotal * 1",
      title: "Identity Multiplication (x * 1)",
      reason: "Multiplying by 1 leaves output state identical.",
      luminance: 0.0,
      status: "Verified Ghost Line",
    },
    {
      line: 7,
      code: "subtotal = subtotal + 0",
      title: "Identity Addition (x + 0)",
      reason: "Adding 0 leaves value invariant.",
      luminance: 0.0,
      status: "Verified Ghost Line",
    },
    {
      line: 8,
      code: "subtotal = subtotal - 0",
      title: "Identity Subtraction (x - 0)",
      reason: "Subtracting 0 exerts zero state leverage.",
      luminance: 0.0,
      status: "Verified Ghost Line",
    },
    {
      line: 9,
      code: "subtotal = subtotal / 1",
      title: "Identity Division (x / 1)",
      reason: "Dividing by 1 is mathematically redundant.",
      luminance: 0.0,
      status: "Verified Ghost Line",
    },
  ]);
  const [luminance, setLuminance] = useState<number>(0.0);
  const [analyzing, setAnalyzing] = useState(false);
  const [logs, setLogs] = useState<string[]>([
    "[SYSTEM] Echo Nullity Desktop IDE Engine Initialized.",
    "[ELECTRON] Context Bridge Connected.",
    "[ENGINE] Python analyze.py loaded. 4 Ghost lines detected in cart_calculator.py.",
  ]);

  const editorRef = useRef<any>(null);
  const decorationsRef = useRef<string[]>([]);

  const addLog = (msg: string) => {
    setLogs((prev) => [...prev.slice(-40), `[${new Date().toLocaleTimeString()}] ${msg}`]);
  };

  // Apply Monaco line highlights whenever findings or editor changes
  useEffect(() => {
    if (!editorRef.current) return;
    const editor = editorRef.current;
    
    const newDecorations = findings.map((f) => ({
      range: {
        startLineNumber: f.line,
        startColumn: 1,
        endLineNumber: f.line,
        endColumn: 100,
      },
      options: {
        isWholeLine: true,
        className: "ghost-code-line-bg",
        inlineClassName: "ghost-code-line-text",
        glyphMarginClassName: "ghost-code-glyph",
        linesDecorationsClassName: "ghost-code-line-decoration",
      },
    }));

    decorationsRef.current = editor.deltaDecorations(decorationsRef.current, newDecorations);
  }, [findings, activeTabPath, editorContent]);

  // Open Folder Handler via IPC
  const handleOpenFolder = async () => {
    if (!window.electronAPI) {
      addLog("[WARN] Running in web mode. Folder dialog requires Electron desktop app.");
      return;
    }

    addLog("[IPC] Invoking dialog:open-folder...");
    const res = await window.electronAPI.openFolder();
    if (res && res.tree) {
      setFolderPath(res.folderPath);
      setFileTree(res.tree);
      addLog(`[IPC] Opened directory: ${res.folderPath}`);
    } else {
      addLog("[IPC] Folder selection cancelled.");
    }
  };

  // Open File Handler
  const handleOpenFile = async (file: FileNode) => {
    if (file.isDirectory) return;

    const existing = openTabs.find((t) => t.path === file.path);
    if (existing) {
      setActiveTabPath(file.path);
      setEditorContent(existing.content);
      runAnalysis(file.path, existing.content);
      return;
    }

    addLog(`[FS] Reading file: ${file.name}`);
    let content = defaultSampleCode;
    if (window.electronAPI && !file.path.startsWith("/mock/")) {
      const res = await window.electronAPI.readFile(file.path);
      if (res.success && res.content !== undefined) {
        content = res.content;
      }
    }

    const newTab = { path: file.path, name: file.name, content };
    setOpenTabs((prev) => [...prev, newTab]);
    setActiveTabPath(file.path);
    setEditorContent(content);

    runAnalysis(file.path, content);
  };

  // Run Python Analyzer via IPC
  const runAnalysis = async (path: string, content: string) => {
    setAnalyzing(true);
    addLog(`[ENGINE] Running Python analyzer on ${path}...`);

    if (window.electronAPI && !path.startsWith("/mock/")) {
      const res = await window.electronAPI.analyzeFile(path);
      if (res && res.findings) {
        setFindings(res.findings);
        setLuminance(res.causal_luminance !== undefined ? res.causal_luminance : (res.findings.length > 0 ? 0.0 : 1.0));
        addLog(`[ENGINE] Analysis complete: ${res.findings.length} ghost lines detected.`);
      }
    } else {
      // Regex analyzer fallback
      const lines = content.split("\n");
      const clientFindings: Finding[] = [];
      lines.forEach((l, i) => {
        if (/(\*\s*1|\+\s*0|-\s*0|\/\s*1)/.test(l)) {
          clientFindings.push({
            line: i + 1,
            code: l.trim(),
            title: "Identity Operation",
            reason: "Mathematical identity operation detected.",
            luminance: 0.0,
            status: "Verified Ghost Line",
          });
        }
      });
      setFindings(clientFindings);
      setLuminance(clientFindings.length > 0 ? 0.0 : 1.0);
      addLog(`[ENGINE] Analysis complete: ${clientFindings.length} ghost lines detected.`);
    }
    setAnalyzing(false);
  };

  // Safe Remove Surgery Handler via IPC
  const handleSafeRemove = async () => {
    if (!activeTabPath || findings.length === 0) return;

    addLog(`[SURGERY] Executing Safe Remove on lines: ${findings.map((f) => f.line).join(", ")}`);
    const targetLines = findings.map((f) => f.line);

    if (window.electronAPI && !activeTabPath.startsWith("/mock/")) {
      const res = await window.electronAPI.safeRemove(activeTabPath, targetLines);
      if (res.success && res.newContent !== undefined) {
        setEditorContent(res.newContent);
        setOpenTabs((prev) =>
          prev.map((t) => (t.path === activeTabPath ? { ...t, content: res.newContent } : t))
        );
        setFindings([]);
        setLuminance(1.0);
        addLog("[SURGERY] Patch applied successfully. 0.0% output state deviation verified.");
      }
    } else {
      // Fallback local remove
      const lines = editorContent.split("\n");
      const newLines = lines.filter((_, idx) => !targetLines.includes(idx + 1));
      const updated = newLines.join("\n");
      setEditorContent(updated);
      setOpenTabs((prev) =>
        prev.map((t) => (t.path === activeTabPath ? { ...t, content: updated } : t))
      );
      setFindings([]);
      setLuminance(1.0);
      addLog("[SURGERY] Safe Remove patch applied locally.");
    }
  };

  const toggleFolder = (path: string) => {
    setExpandedFolders((prev) => ({ ...prev, [path]: !prev[path] }));
  };

  const handleEditorMount: OnMount = (editor, monaco) => {
    editorRef.current = editor;
    
    monaco.editor.defineTheme("echo-dark", {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "8b5cf6", fontStyle: "bold" },
        { token: "identifier", foreground: "22d3ee" },
        { token: "string", foreground: "10b981" },
        { token: "comment", foreground: "6b7280", fontStyle: "italic" },
      ],
      colors: {
        "editor.background": "#050505",
        "editor.foreground": "#e5e7eb",
        "editorLineNumber.foreground": "#4b5563",
        "editorLineNumber.activeForeground": "#22d3ee",
        "editor.lineHighlightBackground": "#0d0d0d",
        "editorGutter.background": "#050505",
      },
    });
    monaco.editor.setTheme("echo-dark");
  };

  const renderTree = (node: FileNode, level = 0) => {
    const isExp = expandedFolders[node.path];
    return (
      <div key={node.path} style={{ paddingLeft: `${level * 10}px` }}>
        {node.isDirectory ? (
          <div>
            <button
              onClick={() => toggleFolder(node.path)}
              className="w-full py-1 px-2 flex items-center gap-1.5 text-xs text-zinc-400 hover:text-white hover:bg-zinc-900/60 rounded font-mono text-left"
            >
              {isExp ? <ChevronDown className="w-3.5 h-3.5 text-cyan-400" /> : <ChevronRight className="w-3.5 h-3.5 text-zinc-500" />}
              <span className="font-semibold text-zinc-300">{node.name}</span>
            </button>
            {isExp && node.children && (
              <div>{node.children.map((child) => renderTree(child, level + 1))}</div>
            )}
          </div>
        ) : (
          <button
            onClick={() => handleOpenFile(node)}
            className={`w-full py-1 px-2 flex items-center gap-1.5 text-xs font-mono text-left rounded transition-colors ${
              activeTabPath === node.path
                ? "bg-cyan-950/60 text-cyan-300 border border-cyan-500/40 font-bold"
                : "text-zinc-400 hover:text-white hover:bg-zinc-900/40"
            }`}
          >
            <FileText className="w-3.5 h-3.5 text-cyan-400" />
            <span>{node.name}</span>
          </button>
        )}
      </div>
    );
  };

  return (
    <div className="flex flex-col h-screen w-screen bg-[#050505] text-white font-sans overflow-hidden select-none">
      
      {/* 1. Header Navigation Bar */}
      <header className="h-12 bg-[#0a0a0a] border-b border-[#1f1f1f] flex items-center justify-between px-4 text-xs font-mono shrink-0 z-20">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-cyan-400 animate-ping" />
            <span className="font-heading font-bold text-sm text-white tracking-tight">
              Echo Nullity IDE
            </span>
            <span className="px-2 py-0.5 text-[9px] text-cyan-400 bg-cyan-950/80 border border-cyan-500/30 rounded-full">
              ELECTRON V1.0
            </span>
          </div>

          <button
            onClick={handleOpenFolder}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#141414] hover:bg-[#1f1f1f] border border-[#262626] text-zinc-200 transition-all"
          >
            <FolderOpen className="w-3.5 h-3.5 text-cyan-400" />
            <span>Open Folder</span>
          </button>

          {folderPath && (
            <span className="text-zinc-500 truncate max-w-xs">
              Project: <span className="text-zinc-300">{folderPath}</span>
            </span>
          )}
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => activeTabPath && runAnalysis(activeTabPath, editorContent)}
            disabled={analyzing}
            className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-purple-950/70 hover:bg-purple-900/80 border border-purple-500/40 text-purple-300 font-bold transition-all"
          >
            <Play className="w-3.5 h-3.5 fill-purple-400" />
            <span>{analyzing ? "Analyzing AST..." : "Run Tomography"}</span>
          </button>

          <button
            onClick={handleSafeRemove}
            disabled={findings.length === 0}
            className="flex items-center gap-1.5 px-4 py-1.5 rounded-xl bg-cyan-400 hover:bg-cyan-300 text-black font-bold shadow-cyan-glow transition-all disabled:opacity-40"
          >
            <Sparkles className="w-3.5 h-3.5 fill-black" />
            <span>Safe Remove ({findings.length})</span>
          </button>
        </div>
      </header>

      {/* 2. Main 4-Pane Workspace Grid (Flex 1) */}
      <div className="flex-1 flex overflow-hidden min-h-0">
        
        {/* Left Sidebar: File Explorer */}
        <div className="w-64 bg-[#0a0a0a] border-r border-[#1f1f1f] flex flex-col justify-between shrink-0">
          <div className="p-3 border-b border-[#1f1f1f] flex items-center justify-between font-mono text-xs">
            <span className="text-zinc-400 uppercase tracking-widest font-bold text-[10px]">Explorer</span>
            <span className="text-cyan-400 text-[10px]">Tree-sitter</span>
          </div>

          <div className="flex-1 p-2 overflow-y-auto space-y-1">
            {fileTree && renderTree(fileTree)}
          </div>

          <div className="p-3 bg-[#0d0d0d] border-t border-[#1f1f1f] font-mono text-[10px] text-zinc-500">
            Python AST Rules Active
          </div>
        </div>

        {/* Center Pane: Monaco Editor & Open Tabs */}
        <div className="flex-1 flex flex-col bg-[#050505] overflow-hidden min-w-0">
          
          {/* Tabs Bar */}
          <div className="h-9 bg-[#0a0a0a] border-b border-[#1f1f1f] flex items-center px-2 gap-1 font-mono text-xs overflow-x-auto shrink-0">
            {openTabs.map((tab) => (
              <button
                key={tab.path}
                onClick={() => {
                  setActiveTabPath(tab.path);
                  setEditorContent(tab.content);
                  runAnalysis(tab.path, tab.content);
                }}
                className={`px-3 py-1 rounded-t-lg flex items-center gap-2 transition-all ${
                  activeTabPath === tab.path
                    ? "bg-[#050505] text-cyan-400 border-t border-x border-cyan-500/40 font-bold"
                    : "text-zinc-400 hover:text-white"
                }`}
              >
                <FileText className="w-3.5 h-3.5" />
                <span>{tab.name}</span>
              </button>
            ))}
          </div>

          {/* Monaco Editor Container */}
          <div className="flex-1 relative min-h-0">
            <Editor
              height="100%"
              language="python"
              theme="echo-dark"
              value={editorContent}
              onChange={(val) => setEditorContent(val || "")}
              onMount={handleEditorMount}
              options={{
                fontSize: 13,
                fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
                lineNumbers: "on",
                minimap: { enabled: false },
                scrollBeyondLastLine: false,
                automaticLayout: true,
                padding: { top: 12 },
              }}
            />
          </div>
        </div>

        {/* Right Pane: Tomography Analysis Panel */}
        <div className="w-80 bg-[#0a0a0a] border-l border-[#1f1f1f] flex flex-col justify-between p-4 space-y-4 shrink-0 overflow-y-auto">
          <div className="space-y-4">
            
            {/* Header */}
            <div className="pb-3 border-b border-[#1f1f1f] flex items-center justify-between">
              <span className="font-heading font-bold text-sm text-white">Tomography Panel</span>
              <span className="px-2 py-0.5 rounded-full bg-cyan-950/80 border border-cyan-500/30 text-cyan-300 font-mono text-[10px]">
                Luminance: {luminance.toFixed(2)}
              </span>
            </div>

            {/* Causal Score Summary */}
            <div className="p-3 bg-[#050505] rounded-xl border border-[#1f1f1f] space-y-2 font-mono text-xs">
              <div className="flex justify-between">
                <span className="text-zinc-400">Causal Impact:</span>
                <span className="text-cyan-400 font-bold">{luminance === 0.0 ? "0.00%" : "100.00%"}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-zinc-400">Ghost Lines:</span>
                <span className="text-purple-400 font-bold">{findings.length}</span>
              </div>
            </div>

            {/* Findings List */}
            <div className="space-y-2">
              <span className="text-xs font-mono text-zinc-400 uppercase tracking-widest font-bold">
                Detected Vacuous Lines
              </span>

              <div className="space-y-2 max-h-72 overflow-y-auto font-mono text-xs">
                {findings.length > 0 ? (
                  findings.map((f, i) => (
                    <div key={i} className="p-3 bg-[#050505] rounded-xl border border-cyan-500/30 space-y-1">
                      <div className="flex items-center justify-between text-cyan-400 font-bold">
                        <span>Line {f.line}</span>
                        <span className="text-[10px] bg-purple-950/80 px-1.5 py-0.5 rounded border border-purple-500/30">
                          {f.title}
                        </span>
                      </div>
                      <div className="text-zinc-300 font-mono bg-[#111111] p-1.5 rounded truncate">
                        {f.code}
                      </div>
                      <p className="text-[11px] text-zinc-400 font-sans leading-tight">
                        {f.reason}
                      </p>
                    </div>
                  ))
                ) : (
                  <div className="p-4 bg-[#050505] rounded-xl border border-[#1f1f1f] text-center text-zinc-500 text-xs font-mono">
                    No vacuous ghost lines detected. Code is causally optimal.
                  </div>
                )}
              </div>
            </div>

          </div>

          {/* Action Trigger */}
          <button
            onClick={handleSafeRemove}
            disabled={findings.length === 0}
            className="w-full py-3 px-4 rounded-24 bg-cyan-400 hover:bg-cyan-300 text-black font-bold text-xs flex items-center justify-center gap-2 shadow-cyan-glow transition-all disabled:opacity-40"
          >
            <Zap className="w-4 h-4 fill-black" />
            <span>Apply Safe Remove Surgery</span>
          </button>
        </div>

      </div>

      {/* 3. Bottom Console Panel */}
      <div className="h-28 bg-[#070707] border-t border-[#1f1f1f] p-3 flex flex-col justify-between font-mono text-xs shrink-0 z-20">
        <div className="flex items-center justify-between text-zinc-500 text-[10px] pb-1 border-b border-[#181818]">
          <div className="flex items-center gap-2">
            <TerminalIcon className="w-3.5 h-3.5 text-cyan-400" />
            <span className="text-zinc-300 font-bold">IPC ENGINE CONSOLE LOGS</span>
          </div>
          <span>Python AST Analyzer • Petgraph DFG</span>
        </div>

        <div className="flex-1 overflow-y-auto space-y-1 pt-1 text-[11px] text-zinc-400">
          {logs.map((log, idx) => (
            <div key={idx} className="leading-tight">
              {log}
            </div>
          ))}
        </div>
      </div>

    </div>
  );
}
