/**
 * NEXUS CODEX HARNESS TOOL - SWARM EXECUTE
 * Executes a previously planned multi-agent swarm with dependency scheduling,
 * isolated subagent workspaces, structured fan-in aggregation, and conflict detection.
 */

const { swarmOrchestrator: defaultSwarmOrchestrator } = require('../SwarmOrchestrator');
const secretFilter = require('../../../security/secretFilter');

const SwarmExecuteTool = {
  name: 'swarm_execute',
  description: 'Executes a previously planned multi-agent swarm using dependency graph scheduling, isolated workspaces, structured fan-in aggregation, and conflict detection.',
  inputSchema: {
    type: 'object',
    properties: {
      swarmId: {
        type: 'string',
        description: 'Unique identifier of the swarm plan to execute (generated by swarm_plan)',
      },
    },
    required: ['swarmId'],
  },
  requiresApproval: false,

  async execute(args = {}, context = {}) {
    if (!args || typeof args !== 'object') {
      return {
        success: false,
        error: 'Arguments must be an object containing "swarmId"',
      };
    }

    const { swarmId } = args;

    if (!swarmId || typeof swarmId !== 'string' || !swarmId.trim()) {
      return {
        success: false,
        error: 'Argument "swarmId" must be a non-empty string',
      };
    }

    const orchestrator = context.swarmOrchestrator || context.runtime?.swarmOrchestrator || defaultSwarmOrchestrator;
    const cleanSwarmId = swarmId.trim();

    const record = orchestrator.activeSwarms.get(cleanSwarmId);
    if (!record) {
      return {
        success: false,
        error: `Swarm "${cleanSwarmId}" not found. Create a plan first using swarm_plan.`,
      };
    }

    // Parent ownership boundary check
    if (
      record.plan &&
      record.plan.parentThreadId &&
      context.threadId &&
      record.plan.parentThreadId !== context.threadId
    ) {
      return {
        success: false,
        error: `Permission Denied: Swarm "${cleanSwarmId}" belongs to parent thread "${record.plan.parentThreadId}", not "${context.threadId}".`,
      };
    }

    const hasMockResponses = Boolean(context.mockResponses || record.plan.metadata?.mockResponses);
    const execOptions = {
      workspacePath: context.workspacePath || record.plan.metadata?.workspacePath || process.cwd(),
      approvalMode: context.approvalMode || 'strict',
      mockResponses: context.mockResponses || record.plan.metadata?.mockResponses,
      modelHandler: hasMockResponses ? undefined : context.modelHandler,
      providerId: context.providerId || record.plan.metadata?.providerId,
      modelId: context.modelId || record.plan.metadata?.modelId,
      useWorkerRuntime: context.useWorkerRuntime,
      autoAdopt: Boolean(context.autoAdopt),
    };

    try {
      const outcome = await orchestrator.executeSwarm(record.plan, execOptions);

      return {
        success: outcome.success,
        swarmId: outcome.swarmId,
        status: outcome.status,
        goal: outcome.goal,
        taskCount: outcome.taskCount,
        completedTaskCount: outcome.completedTaskCount,
        failedTaskCount: outcome.failedTaskCount,
        skippedTaskCount: outcome.skippedTaskCount,
        durationMs: outcome.durationMs,
        summaries: outcome.summaries,
        findings: outcome.findings,
        changedFiles: outcome.changedFiles,
        changeSets: (outcome.changeSets || []).map((cs) => ({
          changeSetId: cs.changeSetId || cs.id,
          filesCount: (cs.files || cs.edits || []).length,
          files: (cs.files || cs.edits || []).map((f) => f.filePath || f.path),
          status: cs.status,
          risk: cs.risk?.overallRiskLevel || null,
        })),
        conflicts: outcome.conflicts ? {
          hasConflicts: Boolean(outcome.conflicts.hasConflicts),
          category: outcome.conflicts.category,
          conflictingFiles: outcome.conflicts.conflictingFiles || [],
          conflicts: (outcome.conflicts.conflicts || []).map((c) => ({
            filePath: c.filePath,
            category: c.category,
            reason: c.reason,
            changeSetIds: c.changeSetIds || (c.changeSetId ? [c.changeSetId] : []),
          })),
        } : { hasConflicts: false, category: 'NO_CONFLICT', conflictingFiles: [], conflicts: [] },
        verification: outcome.verification,
        adoptionResult: outcome.adoptionResult ? {
          success: outcome.adoptionResult.success,
          changeSetId: outcome.adoptionResult.changeSetId,
          adoptedFiles: outcome.adoptionResult.adoptedFiles,
        } : null,
        taskResults: (outcome.taskResults || []).map((t) => ({
          taskId: t.taskId,
          role: t.role,
          status: t.status,
          summary: t.summary,
          error: t.error,
        })),
        nextRecommendedAction: outcome.success
          ? (outcome.conflicts?.hasConflicts
              ? 'Resolve detected ChangeSet conflicts before applying changes.'
              : (outcome.changeSets?.length > 0 && !outcome.adoptionResult
                  ? 'Review aggregated ChangeSets and apply them using apply_patch or adoptSwarmChanges.'
                  : 'Synthesize findings and provide final response.'))
          : 'Inspect task errors and adjust swarm plan or fallback to direct execution.',
      };
    } catch (err) {
      return {
        success: false,
        error: secretFilter.sanitizeString(err.message || 'Swarm execution failed'),
        swarmId: cleanSwarmId,
      };
    }
  },
};

module.exports = SwarmExecuteTool;
