const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openFolder: () => ipcRenderer.invoke('dialog:open-folder'),
  getDefaultDemoWorkspace: () => ipcRenderer.invoke('engine:get-default-demo-workspace'),
  readDir: (dirPath) => ipcRenderer.invoke('fs:read-dir', dirPath),
  readFile: (filePath) => ipcRenderer.invoke('fs:read-file', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('fs:write-file', filePath, content),
  fileExists: (filePath) => ipcRenderer.invoke('fs:file-exists', filePath),
  analyzeFile: (payload) => ipcRenderer.invoke('engine:analyze', payload),
  previewSafeRemove: (filePath) => ipcRenderer.invoke('engine:preview-safe-remove', filePath),
  applySafeRemove: (filePath, transformedContent) => ipcRenderer.invoke('engine:apply-safe-remove', filePath, transformedContent),
  restoreBackup: (filePath) => ipcRenderer.invoke('engine:restore-backup', filePath),
  scanWorkspace: (workspacePath) => ipcRenderer.invoke('engine:scan-workspace', workspacePath),
  verifyEquivalence: (filePath, transformedContent) => ipcRenderer.invoke('engine:verify-equivalence', filePath, transformedContent),
  buildWorkspaceGraph: (workspacePath) => ipcRenderer.invoke('engine:build-workspace-graph', workspacePath),
  loadWorkspaceState: () => ipcRenderer.invoke('state:load'),
  saveWorkspaceState: (state) => ipcRenderer.invoke('state:save', state),
  exportWorkspaceReport: (payload) => ipcRenderer.invoke('report:export', payload),
  previewSurgery: (payload) => ipcRenderer.invoke('surgery:preview', payload),
  applySurgery: (payload) => ipcRenderer.invoke('surgery:apply', payload),
  undoSurgery: (payload) => ipcRenderer.invoke('surgery:undo', payload),
  verifySurgery: (payload) => ipcRenderer.invoke('surgery:verify', payload),
  searchWorkspace: (payload) => ipcRenderer.invoke('workspace:search', payload),
  detectClones: (workspacePath) => ipcRenderer.invoke('engine:detect-clones', workspacePath),
  scanStructuralClones: (workspacePath) => ipcRenderer.invoke('clone:scan', workspacePath),
  detectSemanticClones: (workspacePath) => ipcRenderer.invoke('engine:detect-semantic-clones', workspacePath),
  scanSemanticClones: (workspacePath) => ipcRenderer.invoke('semantic:scan', workspacePath),
  calculateLuminance: (workspacePath) => ipcRenderer.invoke('engine:calculate-luminance', workspacePath),
  listHistory: () => ipcRenderer.invoke('history:list'),
  getHistory: (id) => ipcRenderer.invoke('history:get', id),
  restoreHistory: (id) => ipcRenderer.invoke('history:restore', id),
  appendHistory: (entry) => ipcRenderer.invoke('history:append', entry),
  exportPldiReport: (workspacePath) => ipcRenderer.invoke('report:export-pldi', workspacePath),
  generateFingerprint: (filePath) => ipcRenderer.invoke('behavior:fingerprint', filePath),
  compareFingerprints: (fingerprintA, fingerprintB) => ipcRenderer.invoke('behavior:compare-fingerprints', { fingerprint_a: fingerprintA, fingerprint_b: fingerprintB }),
  analyzeBehaviorHistory: (payload) => ipcRenderer.invoke('behavior:history', payload),
  calculateImpactRadius: (payload) => ipcRenderer.invoke('behavior:impact-radius', payload),
  calculatePropagationTimeline: (payload) => ipcRenderer.invoke('behavior:propagation-timeline', payload),
  calculateBlastRadius: (payload) => ipcRenderer.invoke('behavior:blast-radius', payload),
  runCounterfactualAnalysis: (payload) => ipcRenderer.invoke('behavior:counterfactual', payload),
  evaluatePatchFirewall: (payload) => ipcRenderer.invoke('behavior:patch-firewall', payload),
  evaluateRepositoryFirewall: (payload) => ipcRenderer.invoke('behavior:repository-firewall', payload),
  analyzeSemanticIntentDrift: (payload) => ipcRenderer.invoke('behavior:semantic-intent-drift', payload),
  getBDGGraph: (workspacePath) => ipcRenderer.invoke('bdg:getGraph', workspacePath),
  queryBDGSymbolDependencies: (symbol, relPath, line) => ipcRenderer.invoke('bdg:querySymbolDependencies', { symbol, relPath, line }),
  updateBDGFile: (fullPath, content) => ipcRenderer.invoke('bdg:updateFile', { fullPath, content }),
  calculateBDGBlastRadius: (symbol, relPath, line) => ipcRenderer.invoke('bdg:calculateBlastRadius', { symbol, relPath, line }),
  getRuntimeTelemetry: (nodeId) => ipcRenderer.invoke('runtime:getTelemetry', nodeId),
  getRuntimeCallChainComparison: (nodeId) => ipcRenderer.invoke('runtime:getCallChainComparison', nodeId),
  getRuntimeSessions: () => ipcRenderer.invoke('runtime:getSessions'),
  recordRuntimeEvent: (event) => ipcRenderer.invoke('runtime:recordEvent', event),
  simulateBDGWhatIf: (symbol, relPath, line, operation, secondarySymbol) => ipcRenderer.invoke('bdg:simulateWhatIf', { symbol, relPath, line, operation, secondarySymbol }),
  getBDGBehavioralDiff: (workspacePath) => ipcRenderer.invoke('bdg:getBehavioralDiff', workspacePath),
  generateAIReasoningProposal: (symbol, relPath, line, goal) => ipcRenderer.invoke('ai:generateProposal', { symbol, relPath, line, goal }),
  applyAIMutationProposal: (proposalId, approved) => ipcRenderer.invoke('ai:applyProposal', { proposalId, approved }),
  terminal: {
    create: (options) => ipcRenderer.invoke('terminal:create', options),
    write: (id, data) => ipcRenderer.invoke('terminal:write', { id, data }),
    resize: (id, cols, rows) => ipcRenderer.invoke('terminal:resize', { id, cols, rows }),
    kill: (id) => ipcRenderer.invoke('terminal:kill', id),
    restart: (id) => ipcRenderer.invoke('terminal:restart', id),
    list: () => ipcRenderer.invoke('terminal:list'),
    onData: (callback) => {
      const listener = (event, arg) => callback(arg);
      ipcRenderer.on('terminal:data', listener);
      return () => ipcRenderer.removeListener('terminal:data', listener);
    },
    onExit: (callback) => {
      const listener = (event, arg) => callback(arg);
      ipcRenderer.on('terminal:exit', listener);
      return () => ipcRenderer.removeListener('terminal:exit', listener);
    },
  },
  git: {
    status: (workspacePath) => ipcRenderer.invoke('git:status', workspacePath),
    diff: (workspacePath, file, staged) => ipcRenderer.invoke('git:diff', { workspacePath, file, staged }),
    stage: (workspacePath, file) => ipcRenderer.invoke('git:stage', { workspacePath, file }),
    unstage: (workspacePath, file) => ipcRenderer.invoke('git:unstage', { workspacePath, file }),
    stageAll: (workspacePath) => ipcRenderer.invoke('git:stageAll', workspacePath),
    unstageAll: (workspacePath) => ipcRenderer.invoke('git:unstageAll', workspacePath),
    commit: (workspacePath, message) => ipcRenderer.invoke('git:commit', { workspacePath, message }),
    branches: (workspacePath) => ipcRenderer.invoke('git:branches', workspacePath),
    checkout: (workspacePath, branch) => ipcRenderer.invoke('git:checkout', { workspacePath, branch }),
    createBranch: (workspacePath, branch) => ipcRenderer.invoke('git:createBranch', { workspacePath, branch }),
    discard: (workspacePath, file) => ipcRenderer.invoke('git:discard', { workspacePath, file }),
  },
  search: {
    run: (payload) => ipcRenderer.invoke('search:run', payload),
    replace: (payload) => ipcRenderer.invoke('search:replace', payload),
    replaceAll: (payload) => ipcRenderer.invoke('search:replaceAll', payload),
    cancel: (id) => ipcRenderer.invoke('search:cancel', id),
  },
  ai: {
    codeAction: (payload) => ipcRenderer.invoke('ai:code-action', payload),
  },
  agent: {
    run: (payload) => ipcRenderer.invoke('agent:run', payload),
  },
  recovery: {
    save: (payload) => ipcRenderer.invoke('recovery:save', payload),
    load: (workspacePath) => ipcRenderer.invoke('recovery:load', workspacePath),
    clear: (workspacePath) => ipcRenderer.invoke('recovery:clear', workspacePath),
    list: () => ipcRenderer.invoke('recovery:list'),
    checkCrash: () => ipcRenderer.invoke('recovery:check-crash'),
  },
  tests: {
    discover: (workspacePath) => ipcRenderer.invoke('test:discover', workspacePath),
    run: (payload) => ipcRenderer.invoke('test:run', payload),
    runFile: (payload) => ipcRenderer.invoke('test:run-file', payload),
    runAll: (payload) => ipcRenderer.invoke('test:run-all', payload),
    coverage: (payload) => ipcRenderer.invoke('test:coverage', payload),
  },
  profiler: {
    python: (payload) => ipcRenderer.invoke('profiler:python', payload),
    javascript: (payload) => ipcRenderer.invoke('profiler:javascript', payload),
    memory: (payload) => ipcRenderer.invoke('profiler:memory', payload),
    react: (payload) => ipcRenderer.invoke('profiler:react', payload),
    export: (payload) => ipcRenderer.invoke('profiler:export', payload),
  },
  security: {
    scan: (workspacePath) => ipcRenderer.invoke('security:scan', workspacePath),
    export: (payload) => ipcRenderer.invoke('security:export', payload),
  },
  snapshots: {
    create: (payload) => ipcRenderer.invoke('snapshot:create', payload),
    list: (workspacePath) => ipcRenderer.invoke('snapshot:list', workspacePath),
    get: (payload) => ipcRenderer.invoke('snapshot:get', payload),
    compare: (payload) => ipcRenderer.invoke('snapshot:compare', payload),
    restoreFile: (payload) => ipcRenderer.invoke('snapshot:restore-file', payload),
    restoreWorkspace: (payload) => ipcRenderer.invoke('snapshot:restore-workspace', payload),
    delete: (payload) => ipcRenderer.invoke('snapshot:delete', payload),
  },
  hardening: {
    checkHealth: () => ipcRenderer.invoke('health:check'),
    reportCrash: (error, context) => ipcRenderer.invoke('crash:report', { error, context }),
    listCrashes: () => ipcRenderer.invoke('crash:list'),
    log: (level, category, message, meta) => ipcRenderer.invoke('logger:log', { level, category, message, meta }),
    getRecentLogs: (limit) => ipcRenderer.invoke('logger:recent', limit),
    getTelemetry: () => ipcRenderer.invoke('telemetry:get'),
    setTelemetry: (enabled) => ipcRenderer.invoke('telemetry:set', enabled),
    trackTelemetry: (eventName) => ipcRenderer.invoke('telemetry:track', eventName),
  },
  runPythonFile: (filePath) => ipcRenderer.invoke('python:run-file', filePath),
  onPythonOutput: (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('python:output', listener);
    return () => ipcRenderer.removeListener('python:output', listener);
  },
});
